### ISSUE TITLE
DRAM size 질문

### ISSUE THREAD

**Issue by Csoyee** [vldbhw/sector_level_mapping_FTL#6]
@vldbhw @hgh4554 

p2l table을 sector별로 관리하게 되면서 misc_metadata 크기가 커져서 logging같은 걸 할 때 FTL_BUF를 거쳐서 nand에 쓰는데 FTL_BUF보다 misc_metadata가 커질 수도 있을 것 같은 상황이 발생했는데 정확한 수치를 잘 몰라서

```
질문1
- MAPBLKS_PER_BANK 크기가 SECTOR_MAP_TABLE이랑 연관되어 있는데 대략 몇 정도 될까?

질문2
- DRAM에 추가한 것들 총 합해서 현재 쓰고 있는 dram용량은 어느정도 되는지 아니??
```

**Comment by MinjiKang9** [comment]
질문1 답변)
Sector level mapping table를 caching한 table의 크기는 8MB정도 되고, 
해당 table을 관리하는 또 다른 table의 크기는 1MB정도로 잡았음

질문2 답변)
변경전 기존의 Dram Segmentation부분의 크기 합은 아래와 같음

> (NUM_RD_BUFFERS * BYTES_PER_PAGE)+(NUM_WR_BUFFERS * BYTES_PER_PAGE)+(NUM_COPY_BUFFERS * BYTES_PER_PAGE) + (NUM_FTL_BUFFERS * BYTES_PER_PAGE) + (NUM_HIL_BUFFERS * BYTES_PER_PAGE) + (NUM_TEMP_BUFFERS * BYTES_PER_PAGE) + (((NUM_VBLKS / 8) + DRAM_ECC_UNIT - 1) / DRAM_ECC_UNIT * DRAM_ECC_UNIT) + ((NUM_BANKS * VBLKS_PER_BANK * sizeof(UINT16) + BYTES_PER_SECTOR - 1) / BYTES_PER_SECTOR * BYTES_PER_SECTOR)

여기에 현재 추가한 질문 1 부분을 더하면 현재 사용하고 있는 dram 용량일 것 같아
안에 변수값들은 취사선택해서 사용하는 것 같아서, 어떤식으로 선택하는지를 알아야 전체 용량을 알 수 있을 것 같아
